[build]
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
